Update main.py
deleted two lines because
Handler.send_response(200, response) was throwing AttributeError: 'int' object has no attribute 'log_request'
i dont know why, so i just removed it
i guess you dont really need to get a response that says that the program is shutting down, since you'll just *see* it